CI: updated docker commads

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -40,8 +40,21 @@ jobs:
         cp $APP_DIR_ROOT/docker-compose.yml $APP_DIR/docker-compose.yml
 
         echo "Restarting the containers..."
+        docker-compose down || {
+          echo "Error: Failed to stop the containers."
+          exit 1
+        }
 
-        docker-compose down || true
+        docker stop r2wiki_flask || {
+          echo "Error: Failed to stop the app container."
+          exit 1
+        }
+
+        docker rm r2wiki_flask || {
+          echo "Error: Failed to remove the app container."
+          exit 1
+        }
+
         docker-compose up -d || {
           echo "Error: Failed to start the containers."
           exit 1
